export const defaultSeo = {
  id: 1,
  sports_idi: 1,
  ceo_title: "",
  ceo_description: "",
  ceo_keywords: "",
  ceo_h: "",
  ceo_short_description_for_h: "",
  ceo_photo: "",
  ceo_text: "",
  page: "",
  created_at: "",
  updated_at: "",
  sport_all: "",
  country_all: "",
  league_all: "",
};
